### ISSUE TITLE
Scroll event not fire in React

### ISSUE THREAD

**Issue by grogou** [LottieFiles/lottie-interactivity#58]
Hi there. 

I am creating the integration of lottie in our wordpress plugin.
The wordpress editor is react app, so the problem is the scroll event is not fire.
Can you help me with this, is it bug or no?

Thank you very much.

**Comment by grogou** [comment]
Or can we add 3rd parametr `true` for listener. `    window.addEventListener('scroll', this.#scrollHandler, true);`
It will help on react.

**Comment by samuelOsborne** [comment]
Hi @grogou,

Scrolling on react apps seems to work on my end, I've made this code sand box to show you how I set up playing on scroll with the second lottie:

https://codesandbox.io/s/lottie-react-direction-test-ysj6p?file=/src/App.js


This is using our lottie-react player available here:
https://github.com/LottieFiles/lottie-react

**Comment by grogou** [comment]
@samuelOsborne I am using non react lib in my app, is it the problem?

**Comment by samuelOsborne** [comment]
For the player @grogou ?

**Comment by grogou** [comment]
Yes.

**Comment by samuelOsborne** [comment]
@grogou which player are you using? Can you link please. And share a snippet of your implementation

**Comment by grogou** [comment]
```
import {useEffect, useRef, useState} from "@wordpress/element";
import '@lottiefiles/lottie-player';
import {create} from '@lottiefiles/lottie-interactivity';

export default (props) => {

    const {
        attributes: {
            id,
            url,
            mode,
            state,
            type,
            count,
            speed,
            delay,
            visibility_start,
            visibility_end,
            loop_after_scroll
        },
        setAttributes,
        clientId
    } = props;

    const lottie = useRef(null);
    const [interactivity, setInteractivity] = useState(null);

    useEffect(() => {
            let actions = {};
            if (mode === 'chain') {
                actions = [
                    {
                        state: state,
                        forceFlag: true,
                        loop: count && state === 'loop' ? count : null,
                        speed: speed,
                        delay: delay * 1000
                    }
                ];
            }
            if (mode === 'scroll') {
                actions = [
                    {
                        visibility: [visibility_start / 100, visibility_end / 100],
                        type: "seek",
                        frames: [0, lottie?.current?._lottie?.totalFrames],
                    }
                ];
                if (loop_after_scroll && type === 'seek') {
                    actions.push(
                        {
                            visibility: [visibility_end / 100, 1],
                            type: "loop",
                            frames: [0, lottie?.current?._lottie?.totalFrames]
                        }
                    );
                }
            }
            if (lottie.current !== null) {
                if (url) {
                    lottie.current.addEventListener('load', () => {
                        let interactivity = create({
                            player: `#${id}`,
                            mode: mode,
                            actions: actions,
                        });
                        setInteractivity(interactivity);
                    });
                }
                if (interactivity !== null) {
                    interactivity.redefineOptions({
                        player: `#${id}`,
                        mode: mode,
                        actions: actions,
                    });
                }
            }
        },
        [interactivity, url, mode, type, state, speed, count, delay, visibility_start, visibility_end, loop_after_scroll]
    );

    return (
        <div {...useBlockProps()}>
            {url && id !== undefined &&
                <lottie-player
                    ref={lottie}
                    id={id}
                    mode={mode}
                    src={url}
                />
            }
        </div>
    )
};
```

**Comment by grogou** [comment]
Sorry for big part code I removed unnecessary  parts.

**Comment by grogou** [comment]
@samuelOsborne I think the problem is my envirment, when I manual add 

```
window.addEventListener('scroll', (e) => {
     console.log(e)
});
```

it is not working, but when I add `true` as 3rd param it works.

```
window.addEventListener('scroll', (e) => {
     console.log(e)
}, true );
```

**Comment by samuelOsborne** [comment]
@grogou Could you try adding the lottie variable to the useEffect array at the bottom, to make sure the Lottie ref isn't null inside of useEffect

```
[lottie, interactivity, url, mode, type, state, speed, count, delay, visibility_start, visibility_end, loop_after_scroll]
```

**Comment by grogou** [comment]
@samuelOsborne yes sure will try it.

But I found article about this problem on wordpress 

https://make.wordpress.org/core/2021/06/29/blocks-in-an-iframed-template-editor/

It is the iframe problem

**Comment by grogou** [comment]
The interesting part is `But what if the library is using the global window or document and it’s out of your control?`

**Comment by grogou** [comment]
> @grogou Could you try adding the lottie variable to the useEffect array at the bottom, to make sure the Lottie ref isn't null inside of useEffect
> 
> ```
> [lottie, interactivity, url, mode, type, state, speed, count, delay, visibility_start, visibility_end, loop_after_scroll]
> ```

It's not working.

**Comment by grogou** [comment]
And I can share with you the Wordpress developer comment on this problem

https://github.com/WordPress/gutenberg/issues/38692#issuecomment-1035091059

Sorry for me and my questions, but this is interesting case.

**Comment by samuelOsborne** [comment]
@grogou have you tried out what they recommend in the meantime? 

"<p style="box-sizing: border-box; margin: 0px 0px 1.2em; padding: 0px; overflow-wrap: break-word; border: 0px; font-family: &quot;Open Sans&quot;, sans-serif; font-size: 1.05em; font-style: normal; font-weight: 400; outline: 0px; vertical-align: baseline; line-height: 1.6; color: rgb(85, 85, 85); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">In the meantime, you can use the script that is loaded inside the iframe. We’ve loaded all front-end scripts in the iframe to fix these cases, but note that ideally you shouldn’t use scripts loaded in the iframe at all. You can use<span> </span><code style="box-sizing: border-box; font: 0.9em Monaco, Consolas, &quot;Courier New&quot;, monospace; color: rgb(34, 34, 34); border: 0px; margin: 0px; outline: 0px; padding: 0.4em 0.65em; vertical-align: baseline; background: padding-box rgb(241, 241, 241); border-radius: 3px;">defaultView</code><span> </span>to access the script.</p><div class="wp-block-syntaxhighlighter-code " style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-weight: 400; outline: 0px; vertical-align: baseline; color: rgb(85, 85, 85); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: 13px; font-style: inherit; font-weight: inherit; outline: 0px; vertical-align: baseline;"><div id="highlighter_919343" class="syntaxhighlighter nogutter  jscript" style="box-sizing: border-box; margin: 1em 0px !important; padding: 0.5em 1em !important; border: 0px; font-family: inherit; font-size: 1em !important; font-style: inherit; font-weight: inherit; outline: 0px; vertical-align: baseline; width: 605.797px; position: relative !important; overflow: auto hidden !important; background-color: white !important;">

```
const ref = useRefEffect( ( element ) => {  const { ownerDocument } = element;  const { defaultView } = ownerDocument;   // Use the script loaded in the iframe.  // Script are loaded asynchronously, so check is the script is loaded.  // After the dependencies have loaded, the block will re-render.  if ( ! defaultView.jQuery ) {    return;  }   defaultView.jQuery( element ).masonry( … );  return () => {    defaultView.jQuery( element ).masonry( 'destroy' );  }} );const props = useBlockProps( { ref } );

```

"

**Comment by grogou** [comment]
I am trying, but still can't understand how to use lottie on it.

**Comment by samuelOsborne** [comment]
@grogou I've just noticed, could you also try swapping out the 'load' event to 'ready':

```
 lottie.current.addEventListener('ready', () => { ......
 ```
 
 and see how that goes

**Comment by grogou** [comment]
Ah oki, the problem is that 3rd parametr, https://github.com/facebook/react/issues/5042 the React issue. Could you able to add it to lib in new version, or ownerDocument implementation? It can be helpful for me and guys similar me, because the wordpress community can do nice things with this repo. If you need I can mention wordpress devs, in our distinction. they say `Feel free to contact us to mention the issue.`

**Comment by grogou** [comment]
> @grogou I've just noticed, could you also try swapping out the 'load' event to 'ready':
> 
> ```
>  lottie.current.addEventListener('ready', () => { ......
> ```
> 
> and see how that goes

Not working (:

**Comment by samuelOsborne** [comment]
@grogou Will look in to including this in a new version, I'll keep you updated

**Comment by grogou** [comment]
@samuelOsborne thank you very much for your help. I will try to add notice in my plugin about issue, until problem will be fixed. Have a good day and thank you again.

**Comment by grogou** [comment]
@samuelOsborne thank you very much for this fix. And one more question. Is it related bug for me, when I change `url` variable and `src` attribute got rendered with new url why my lottie player play old lottie?

**Comment by samuelOsborne** [comment]
Hi @grogou I've pushed up a beta package on npm: 

https://www.npmjs.com/package/@lottiefiles/lottie-interactivity/v/1.3.4-beta.0

can you let me know if this resolves your issue please.

For your second questions, I'm not sure what you mean, could you explain to me again please?

**Comment by grogou** [comment]
Thank you, will check it now.

About second question.
![image](https://user-images.githubusercontent.com/10712881/154482636-110f2658-dbb5-4778-8de0-a047d51fb189.png)

When url state changed and component get rerendered with new url, lottie still animate old one.

**Comment by grogou** [comment]
> Hi @grogou I've pushed up a beta package on npm:
> 
> https://www.npmjs.com/package/@lottiefiles/lottie-interactivity/v/1.3.4-beta.0
> 
> can you let me know if this resolves your issue please.
> 
> For your second questions, I'm not sure what you mean, could you explain to me again please?

It is still not working becouse of this 3rd param in listener I guess.
https://github.com/WordPress/gutenberg/issues/38692#issuecomment-1035091059
![image](https://user-images.githubusercontent.com/10712881/154484425-e1579a14-8490-479d-b249-a22f3e96b36f.png)

**Comment by samuelOsborne** [comment]
@grogou I've added use capture to this version, please let me know if it works for you:

https://www.npmjs.com/package/@lottiefiles/lottie-interactivity/v/1.3.4-beta.1

**Comment by grogou** [comment]
I can't find any new examples, is it same doc?

**Comment by samuelOsborne** [comment]
@grogou yes, use scrolling the same way you did before, I've added useCapture internally on the scroll listener

**Comment by grogou** [comment]
@samuelOsborne yes it's works now, thx very much you best)))

**Comment by samuelOsborne** [comment]
@grogou Great, I'll push this in to the master branch and release soon, I'll ping you here and close the issue

**Comment by grogou** [comment]
And about second question. Is thery a way to destroy current lottie after lottie src change and reinit it.

**Comment by grogou** [comment]
@samuelOsborne because of I changed lottie url, but it is still play old one.

![image](https://user-images.githubusercontent.com/10712881/154490654-a43e065a-0332-43a9-baea-359bf92e7beb.png)

**Comment by samuelOsborne** [comment]
@grogou Yes, on the lottie-player, there is a destroy() method available

**Comment by samuelOsborne** [comment]
@grogou In which case do you need to change the URL of the lottie? It might be possible with lottie-interactivity directly

**Comment by grogou** [comment]
@samuelOsborne I have integration of your lib in my wordpress contructor and use case is when user need to change lottie in editor.
![image](https://user-images.githubusercontent.com/10712881/154491534-fee97e10-e229-416e-9bd7-415bb36e1bd2.png)

**Comment by grogou** [comment]
Can I change url with `redefineOptions` ?
![image](https://user-images.githubusercontent.com/10712881/154491711-72d8f11c-c0be-4f4e-b47c-d34e59034d27.png)

**Comment by samuelOsborne** [comment]
@grogou Yep you can:

```
  interactivity.redefineOptions({
    player: '#firstLottie',
    mode: 'chain',
    actions: [
      {
        path: 'https://assets6.lottiefiles.com/packages/lf20_yefgzddc.json'
      },
    ],
  });
```

only works with chain mode though.

Otherwise the lottie-player element can be called with the destroy method

**Comment by grogou** [comment]
@samuelOsborne thank you, will do it.

**Comment by samuelOsborne** [comment]
@grogou I've merged, this is out in version 1.3.5. 

Cheers, closing this now.

**Comment by icebearlabs** [comment]
> Hi @grogou,
> 
> Scrolling on react apps seems to work on my end, I've made this code sand box to show you how I set up playing on scroll with the second lottie:
> 
> https://codesandbox.io/s/lottie-react-direction-test-ysj6p?file=/src/App.js
> 
> This is using our lottie-react player available here: https://github.com/LottieFiles/lottie-react

Hey @samuelOsborne, do you have any idea what I'm doing wrong here? 

```
import { create } from "@lottiefiles/lottie-interactivity";
import { Player } from "@lottiefiles/react-lottie-player";
import { createRef, memo, useState } from "react";
import { Block } from "../../../components";

export const Customization = memo(() => {
  const lottieRef = createRef<any>();
  const [lottie, setLottie] = useState<any>(null);

  return (
    <Block>
      <div className="flex flex-col p-16">
        <Player
          ref={lottieRef}
          lottieRef={(instance) => {
            setLottie(instance);
          }}
          onEvent={(event) => {
            if (event === "load") {
              create({
                mode: "scroll",
                player: lottie,
                actions: [
                  {
                    visibility: [0.5, 1],
                    type: "seek",
                    frames: [0, 100],
                  },
                ],
              });
            }
          }}
          controls={true}
          autoplay={false}
          loop={false}
          src={"/animations/monster.json"}
          style={{ width: "320px" }}
        ></Player>
      </div>
    </Block>
  );
});
```

It just doesn't do anything on scroll, even though I copied your code to the last bit. 

Is the issue that it's a FunctionComponent? I have no idea what the problem is, it looks exactly like your example otherwise.

**Comment by icebearlabs** [comment]
GOT IT! For anyone finding this and using @samuelOsborne's example and then nothing happening: Check the amount of frames your file has. For me that was the problem. The first 100 frames didn't really do much, so I didn't see any animation. Also the visibility [0.5, 1] killed a lot of the animation, so set that to [0,1] and see how it works.
